# Gradle runtime
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Environment Properties
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.20
forge_version_range=[47,)
loader_version_range=[47,)
create_version=6.0.8-289
ponder_version=1.0.91
flywheel_version=1.0.5
registrate_version=MC1.20-1.3.3

## Mod Properties
mod_id=create_double_ore
mod_name=Create Ore Doubling
mod_license=MIT
mod_version=1.0.2
mod_group_id=de.pasuki.create_double_ore
mod_authors=Pasuki
mod_description=Create addon that adds crushing-based ore doubling recipes for raw ores and raw ore blocks.
